/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as ApiTransactionsIndexRouteImport } from './routes/api/transactions/index'
import { Route as ApiTransactionsAmtboundsRouteImport } from './routes/api/transactions/amtbounds'
import { Route as ApiTransactionsStatsIndexRouteImport } from './routes/api/transactions/stats/index'
import { Route as ApiTransactionsStatsByUserRouteImport } from './routes/api/transactions/stats/by-user'
import { Route as ApiTransactionsStatsByMonthUserRouteImport } from './routes/api/transactions/stats/by-month-user'
import { Route as ApiTransactionsStatsByCategoryRouteImport } from './routes/api/transactions/stats/by-category'

const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsIndexRoute = ApiTransactionsIndexRouteImport.update({
  id: '/api/transactions/',
  path: '/api/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsAmtboundsRoute =
  ApiTransactionsAmtboundsRouteImport.update({
    id: '/api/transactions/amtbounds',
    path: '/api/transactions/amtbounds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTransactionsStatsIndexRoute =
  ApiTransactionsStatsIndexRouteImport.update({
    id: '/api/transactions/stats/',
    path: '/api/transactions/stats/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTransactionsStatsByUserRoute =
  ApiTransactionsStatsByUserRouteImport.update({
    id: '/api/transactions/stats/by-user',
    path: '/api/transactions/stats/by-user',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTransactionsStatsByMonthUserRoute =
  ApiTransactionsStatsByMonthUserRouteImport.update({
    id: '/api/transactions/stats/by-month-user',
    path: '/api/transactions/stats/by-month-user',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTransactionsStatsByCategoryRoute =
  ApiTransactionsStatsByCategoryRouteImport.update({
    id: '/api/transactions/stats/by-category',
    path: '/api/transactions/stats/by-category',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/api/transactions/amtbounds': typeof ApiTransactionsAmtboundsRoute
  '/api/transactions/': typeof ApiTransactionsIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/api/transactions/stats/by-category': typeof ApiTransactionsStatsByCategoryRoute
  '/api/transactions/stats/by-month-user': typeof ApiTransactionsStatsByMonthUserRoute
  '/api/transactions/stats/by-user': typeof ApiTransactionsStatsByUserRoute
  '/api/transactions/stats/': typeof ApiTransactionsStatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/api/transactions/amtbounds': typeof ApiTransactionsAmtboundsRoute
  '/api/transactions': typeof ApiTransactionsIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/api/transactions/stats/by-category': typeof ApiTransactionsStatsByCategoryRoute
  '/api/transactions/stats/by-month-user': typeof ApiTransactionsStatsByMonthUserRoute
  '/api/transactions/stats/by-user': typeof ApiTransactionsStatsByUserRoute
  '/api/transactions/stats': typeof ApiTransactionsStatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/api/transactions/amtbounds': typeof ApiTransactionsAmtboundsRoute
  '/api/transactions/': typeof ApiTransactionsIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/api/transactions/stats/by-category': typeof ApiTransactionsStatsByCategoryRoute
  '/api/transactions/stats/by-month-user': typeof ApiTransactionsStatsByMonthUserRoute
  '/api/transactions/stats/by-user': typeof ApiTransactionsStatsByUserRoute
  '/api/transactions/stats/': typeof ApiTransactionsStatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/import'
    | '/api/transactions/amtbounds'
    | '/api/transactions/'
    | '/api/users/'
    | '/api/transactions/stats/by-category'
    | '/api/transactions/stats/by-month-user'
    | '/api/transactions/stats/by-user'
    | '/api/transactions/stats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/import'
    | '/api/transactions/amtbounds'
    | '/api/transactions'
    | '/api/users'
    | '/api/transactions/stats/by-category'
    | '/api/transactions/stats/by-month-user'
    | '/api/transactions/stats/by-user'
    | '/api/transactions/stats'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/import'
    | '/api/transactions/amtbounds'
    | '/api/transactions/'
    | '/api/users/'
    | '/api/transactions/stats/by-category'
    | '/api/transactions/stats/by-month-user'
    | '/api/transactions/stats/by-user'
    | '/api/transactions/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ImportRoute: typeof ImportRoute
  ApiTransactionsAmtboundsRoute: typeof ApiTransactionsAmtboundsRoute
  ApiTransactionsIndexRoute: typeof ApiTransactionsIndexRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
  ApiTransactionsStatsByCategoryRoute: typeof ApiTransactionsStatsByCategoryRoute
  ApiTransactionsStatsByMonthUserRoute: typeof ApiTransactionsStatsByMonthUserRoute
  ApiTransactionsStatsByUserRoute: typeof ApiTransactionsStatsByUserRoute
  ApiTransactionsStatsIndexRoute: typeof ApiTransactionsStatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users/'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/': {
      id: '/api/transactions/'
      path: '/api/transactions'
      fullPath: '/api/transactions/'
      preLoaderRoute: typeof ApiTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/amtbounds': {
      id: '/api/transactions/amtbounds'
      path: '/api/transactions/amtbounds'
      fullPath: '/api/transactions/amtbounds'
      preLoaderRoute: typeof ApiTransactionsAmtboundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/stats/': {
      id: '/api/transactions/stats/'
      path: '/api/transactions/stats'
      fullPath: '/api/transactions/stats/'
      preLoaderRoute: typeof ApiTransactionsStatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/stats/by-user': {
      id: '/api/transactions/stats/by-user'
      path: '/api/transactions/stats/by-user'
      fullPath: '/api/transactions/stats/by-user'
      preLoaderRoute: typeof ApiTransactionsStatsByUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/stats/by-month-user': {
      id: '/api/transactions/stats/by-month-user'
      path: '/api/transactions/stats/by-month-user'
      fullPath: '/api/transactions/stats/by-month-user'
      preLoaderRoute: typeof ApiTransactionsStatsByMonthUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/stats/by-category': {
      id: '/api/transactions/stats/by-category'
      path: '/api/transactions/stats/by-category'
      fullPath: '/api/transactions/stats/by-category'
      preLoaderRoute: typeof ApiTransactionsStatsByCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ImportRoute: ImportRoute,
  ApiTransactionsAmtboundsRoute: ApiTransactionsAmtboundsRoute,
  ApiTransactionsIndexRoute: ApiTransactionsIndexRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
  ApiTransactionsStatsByCategoryRoute: ApiTransactionsStatsByCategoryRoute,
  ApiTransactionsStatsByMonthUserRoute: ApiTransactionsStatsByMonthUserRoute,
  ApiTransactionsStatsByUserRoute: ApiTransactionsStatsByUserRoute,
  ApiTransactionsStatsIndexRoute: ApiTransactionsStatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
