/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTransactionsIndexRouteImport } from './routes/api/transactions/index'
import { Route as ApiTransactionsUsersRouteImport } from './routes/api/transactions/users'
import { Route as ApiTransactionsAmtboundsRouteImport } from './routes/api/transactions/amtbounds'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsIndexRoute = ApiTransactionsIndexRouteImport.update({
  id: '/api/transactions/',
  path: '/api/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsUsersRoute = ApiTransactionsUsersRouteImport.update({
  id: '/api/transactions/users',
  path: '/api/transactions/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsAmtboundsRoute =
  ApiTransactionsAmtboundsRouteImport.update({
    id: '/api/transactions/amtbounds',
    path: '/api/transactions/amtbounds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/transactions/amtbounds': typeof ApiTransactionsAmtboundsRoute
  '/api/transactions/users': typeof ApiTransactionsUsersRoute
  '/api/transactions/': typeof ApiTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/transactions/amtbounds': typeof ApiTransactionsAmtboundsRoute
  '/api/transactions/users': typeof ApiTransactionsUsersRoute
  '/api/transactions': typeof ApiTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/transactions/amtbounds': typeof ApiTransactionsAmtboundsRoute
  '/api/transactions/users': typeof ApiTransactionsUsersRoute
  '/api/transactions/': typeof ApiTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/import'
    | '/api/auth/$'
    | '/api/transactions/amtbounds'
    | '/api/transactions/users'
    | '/api/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/import'
    | '/api/auth/$'
    | '/api/transactions/amtbounds'
    | '/api/transactions/users'
    | '/api/transactions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/import'
    | '/api/auth/$'
    | '/api/transactions/amtbounds'
    | '/api/transactions/users'
    | '/api/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ImportRoute: typeof ImportRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTransactionsAmtboundsRoute: typeof ApiTransactionsAmtboundsRoute
  ApiTransactionsUsersRoute: typeof ApiTransactionsUsersRoute
  ApiTransactionsIndexRoute: typeof ApiTransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/': {
      id: '/api/transactions/'
      path: '/api/transactions'
      fullPath: '/api/transactions/'
      preLoaderRoute: typeof ApiTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/users': {
      id: '/api/transactions/users'
      path: '/api/transactions/users'
      fullPath: '/api/transactions/users'
      preLoaderRoute: typeof ApiTransactionsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions/amtbounds': {
      id: '/api/transactions/amtbounds'
      path: '/api/transactions/amtbounds'
      fullPath: '/api/transactions/amtbounds'
      preLoaderRoute: typeof ApiTransactionsAmtboundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ImportRoute: ImportRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTransactionsAmtboundsRoute: ApiTransactionsAmtboundsRoute,
  ApiTransactionsUsersRoute: ApiTransactionsUsersRoute,
  ApiTransactionsIndexRoute: ApiTransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
